apiVersion: v1
kind: Service
{{- with .Values.service }}
metadata:
  name: {{ $.Release.Name }}-service
  labels:
    app: {{ $.Release.Name }}
spec:
  ports:
  {{- if .type.clusterIP }}
    - port: {{ .type.clusterIP.port }}
      targetPort: {{ .type.clusterIP.targetPort }}
      protocol: {{ .type.clusterIP.protocol }}
  selector:
    app: {{ $.Release.Name }}
  type: ClusterIP
  {{- end }}
  {{- if .type.nodePort }}
    - port: {{ .type.nodePort.port }}
      nodePort: {{ .type.nodePort.nodePort }}
      targetPort: {{ .type.nodePort.targetPort }}
      protocol: {{ .type.nodePort.protocol }}
  selector:
    app: {{ $.Release.Name }}
  type: NodePort
  {{- end }}
{{- end }}