apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}-service
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
