apiVersion: v1
kind: Service
{{- with .Values.service }}
metadata:
  name: {{ $.Release.Name }}-service
  labels:
    app: {{ $.Release.Name }}
spec:
  selector:
    app: {{ $.Release.Name }}
  ports:
  {{- if .type.clusterIp }}
    - port: {{ .type.clusterIp.port }}
      targetPort: {{ .type.clusterIp.targetPort }}
      protocol: {{ .type.clusterIp.protocol }}
  {{- end }}
  {{- if .type.nodePort }}
    - port: {{ .type.nodePort.port }}
      targetPort: {{ .type.nodePort.targetPort }}
      protocol: {{ .type.nodePort.protocol }}
  {{- end }}
  
